#include "onda_comp_aarch64.h"
#include "onda_jit.h"
#include "onda_parser.h"
#include "onda_vm.h"

#include <stdio.h>

// static const char* program = "300 0 + 100 * dup + 2 swap * \"test\n\" .s .
// halt";
static const char* program =
    "300 0 + 10 * dup + 2 swap * \"Result is \" .s . halt\0";
// static const char *program = "\"Hello world!\n\" .s halt\0";

int main(int argc, char* argv[]) {
  uint8_t codebuf[1024];
  size_t code_size = sizeof(codebuf);
  size_t entry_pc = 0;
  onda_parse(program, codebuf, &code_size, &entry_pc);

  // Print generated bytecode
  printf("Generated bytecode (%lu bytes):\n", code_size);
  for (int i = 0; i < code_size; i++) {
    if (i % 16 == 0 && i != 0)
      printf("\n");
    printf("%02X ", codebuf[i]);
  }
  printf("\n\n");

  // Compile to machine code (AArch64)
  uint8_t* machine_code = NULL;
  size_t machine_code_size = 0;
  onda_comp_aarch64(codebuf, code_size, &machine_code, &machine_code_size);
  printf("Generated machine code (%lu bytes):\n", machine_code_size);
  for (int i = 0; i < machine_code_size; i++) {
    if (i % 16 == 0 && i != 0)
      printf("\n");
    printf("%02X ", machine_code[i]);
  }
  printf("\n\n");

  // Execute program in VM, starting from entry_pc
  onda_vm_t* vm = onda_vm_new();
  onda_vm_load_code(vm, codebuf, entry_pc, code_size);
  printf("Executing program:\n");
  onda_vm_run(vm);
  printf("stack size: %lu\n", vm->sp);

  // Execute program in JIT
  uint64_t tos = onda_jit_run(machine_code, machine_code_size);
  printf("JIT execution result (TOS): %llu\n", tos);

  onda_vm_free(vm);
  return 0;
}
