#ifndef ONDA_CONFIG_H
#define ONDA_CONFIG_H

#ifndef ONDA_ENABLE_JIT_X86_64
#define ONDA_ENABLE_JIT_X86_64 0
#endif

#ifndef ONDA_ENABLE_JIT_AARCH64
#define ONDA_ENABLE_JIT_AARCH64 0
#endif

#if ONDA_ENABLE_JIT_X86_64 || ONDA_ENABLE_JIT_AARCH64
#define ONDA_CAN_JIT
#endif

#define ONDA_DATA_STACK_SIZE  1024
#define ONDA_FRAME_STACK_SIZE 1024
#define ONDA_CODE_BUF_SIZE 2048
#define ONDA_MAX_FILENAME_LEN  64
#define ONDA_MAX_FILEPATH_LEN  256
#define ONDA_MAX_WORD_NAME_LEN 32
#define ONDA_MAX_IMPORT_DEPTH  64
#define ONDA_HAS_FILESYSTEM 1
//#define ONDA_VM_DEBUG_MODE

#endif // ONDA_CONFIG_H
