"""Keyword and builtin metadata used by hover/completion."""

KEYWORDS = {
    "import": "Import another Onda source file.",
    "if": "Start a conditional block.",
    "then": "Marks the true branch of an if block.",
    "else": "Marks the false branch of an if block.",
    "end": "Closes an if/while block.",
    "while": "Start a while loop.",
    "do": "Marks the loop body.",
    "ret": "Return from current word.",
}

BUILTINS = {
    ".": "Print top stack value.",
    ".s": "Print string.",
    "dup": "Duplicate top stack value.",
    "drop": "Drop top stack value.",
    "swap": "Swap top two stack values.",
    "malloc": "Allocate memory.",
    "free": "Free memory.",
    "fopen": "Open file.",
    "fclose": "Close file.",
    "fread": "Read bytes from file.",
    "memset": "Set memory bytes.",
    "@": "Load value from memory address.",
    "!": "Store value to memory address.",
    "b@": "Load byte from memory address.",
    "b!": "Store byte to memory address.",
    "not": "Logical not.",
    "and": "Logical and.",
    "or": "Logical or.",
    "exit": "Terminate process.",
}

# Standard library words registered in src/onda_std.c (std_fns[]).
STDLIB_FUNCTIONS = {
    ".": "Print top value as unsigned 64-bit integer.",
    ".s": "Print C-string at pointer on stack.",
    ".c": "Print top value as character.",
    "print_u64": "Print value as unsigned 64-bit integer.",
    "print_i64": "Print value as signed 64-bit integer.",
    "print_hex": "Print value in hexadecimal format.",
    "print_ptr": "Print value as pointer address.",
    "print_char": "Print value as character.",
    "print_str": "Print C-string at pointer.",
    "emit": "Alias for print_char.",
    "malloc": "Allocate memory block of given size.",
    "calloc": "Allocate and zero-initialize memory.",
    "free": "Free previously allocated memory.",
    "realloc": "Resize previously allocated memory block.",
    "memcpy": "Copy memory region.",
    "memset": "Fill memory region with byte value.",
    "memcmp": "Compare two memory regions.",
    "strlen": "Return C-string length.",
    "strcmp": "Compare two C-strings.",
    "strncmp": "Compare first n bytes of two C-strings.",
    "strcpy": "Copy C-string into destination buffer.",
    "strncpy": "Copy up to n bytes into destination buffer.",
    "strcat": "Append source string to destination string.",
    "strncat": "Append up to n bytes from source string.",
    "strchr": "Find first matching character in string.",
    "strstr": "Find substring in string.",
    "atoi": "Parse C-string to integer.",
    "strtol": "Parse C-string to long using base.",
    "strtoul": "Parse C-string to unsigned long using base.",
    "fopen": "Open file and return file pointer.",
    "tmpfile": "Create temporary file stream.",
    "fclose": "Close file stream.",
    "fread": "Read items from file stream.",
    "fwrite": "Write items to file stream.",
    "fseek": "Seek to offset in file stream.",
    "ftell": "Get current position in file stream.",
    "fflush": "Flush file stream output.",
    "feof": "Check end-of-file indicator.",
    "ferror": "Check file stream error indicator.",
    "rewind": "Reset file position to start.",
    "clearerr": "Clear EOF and error indicators.",
    "remove": "Delete file by path.",
    "rename": "Rename or move file path.",
    "assert": "Abort with message when condition is false.",
}

STACK_EFFECTS = {
    "import": "( path -- )",
    "if": "( cond -- )",
    "then": "( -- )",
    "else": "( -- )",
    "end": "( -- )",
    "while": "( cond -- )",
    "do": "( -- )",
    "ret": "( -- )",
    ".": "( x -- )",
    ".s": "( str_ptr -- )",
    ".c": "( ch -- )",
    "dup": "( x -- x x )",
    "drop": "( x -- )",
    "swap": "( a b -- b a )",
    "malloc": "( size -- ptr )",
    "calloc": "( count size -- ptr )",
    "free": "( ptr -- )",
    "realloc": "( new_size ptr -- ptr )",
    "memcpy": "( n src dst -- )",
    "memset": "( n value dst -- )",
    "memcmp": "( n ptr2 ptr1 -- cmp )",
    "strlen": "( str -- len )",
    "strcmp": "( str2 str1 -- cmp )",
    "strncmp": "( n str2 str1 -- cmp )",
    "strcpy": "( src dst -- )",
    "strncpy": "( n src dst -- )",
    "strcat": "( src dst -- )",
    "strncat": "( n src dst -- )",
    "strchr": "( ch str -- ptr )",
    "strstr": "( needle haystack -- ptr )",
    "atoi": "( str -- int )",
    "strtol": "( base str -- long )",
    "strtoul": "( base str -- ulong )",
    "fopen": "( mode filename -- file )",
    "tmpfile": "( -- file )",
    "fclose": "( file -- rc )",
    "fread": "( stream count size ptr -- read_count )",
    "fwrite": "( stream count size ptr -- write_count )",
    "fseek": "( stream offset whence -- rc )",
    "ftell": "( stream -- pos )",
    "fflush": "( stream -- rc )",
    "feof": "( stream -- flag )",
    "ferror": "( stream -- flag )",
    "rewind": "( stream -- )",
    "clearerr": "( stream -- )",
    "remove": "( filename -- rc )",
    "rename": "( new_path old_path -- rc )",
    "exit": "( code -- )",
    "assert": "( cond msg -- )",
    "print_u64": "( x -- )",
    "print_i64": "( x -- )",
    "print_hex": "( x -- )",
    "print_ptr": "( ptr -- )",
    "print_char": "( ch -- )",
    "print_str": "( str_ptr -- )",
    "emit": "( ch -- )",
    "@": "( addr -- value )",
    "!": "( value addr -- )",
    "b@": "( addr -- byte )",
    "b!": "( byte addr -- )",
    "not": "( x -- flag )",
    "and": "( a b -- flag )",
    "or": "( a b -- flag )",
}
